### ISSUE TITLE
"Apply filter" does not work

### ISSUE THREAD

**Issue by svades** [camptocamp/demo_geomapfish#64] opened 2018-01-29 12:13 UTC
Project:

- https://geomapfish-demo.camptocamp.net/2.2

Steps to reproduce issue:

- go to https://geomapfish-demo.camptocamp.net/2.2

- delete all layers in layertree

- open the filter

- select OSM map

- add a spatial filter

- choose "apply filter"

- result: nothing happens

Expected result: only the selected buildings are shown

![demo_filter_anwenden](https://user-images.githubusercontent.com/22655359/35509834-0e86c78c-04f6-11e8-829a-dbb889ae9a74.jpg)

The same issue exists on map.geo.test.bs.ch/ngeodesktop

**Comment by llienher** [comment] 2018-02-13 07:52
In the case of our demo, OSM Map is loaded here as backgound layer, this is why it is available in the filter list.

The get data is making a WFS request on the OSM geometries. While not displayed as an overlay on top of the background layer, the WFS geometries are part of the background layer. The intended behavior is the same as doing a mouse selection on the map, but here via the filters as the selection tool.

The 'apply filter' is doing a GetFeature request to MapServer to get only the displayed geometries in the circle, as we can see there is none initially in that layer, so the result here is coherent from this perspective.

I'm closing this issue, but please next report in the ngeo repository, as we prefer to have everything at the same place (or c2cgeoportail for backend issues). We use this only when it is related to demo-only issues, so it would not appear theoretically in any other project.  Plus, I'm not sure everybody is keeping track of the issue list in this repository.  :-)

**Comment by yjacolin** [comment] 2018-02-13 08:18
If Background layer can't be filtered, we should remove it in the list.

**Comment by yjacolin** [comment] 2018-02-13 08:19
Related in some way with https://github.com/camptocamp/ngeo/issues/3468 (wrong user experience)

**Comment by yjacolin** [comment] 2018-02-14 09:51
Work as expected: get data work (via WFS request) not apply filter as it is a WMTS.

**Closed by yjacolin** 2018-02-14 09:51 UTC
